spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://[RDS 주소]:3306/project?servertimezone=UTC
    username: bit
    password: bit
    
  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML5
    cache: false
    template-resolver-order: 0
  
mybatis:
  mapper-locations: com/bitcamp/demo/member/mapper/**/*.xml
  
  
server:
  port: 8081
    
    
    

